### ISSUE TITLE
Moonraker v0.7.1-586 > v0.7.1-587

### ISSUE THREAD

**Issue by JFD8** [Flsun3d/Speeder-pad---printer-firmware#1]
12:05:29 | error: The following untracked working tree files would be overwritten by merge:
-- | --
12:05:29 | moonraker/components/timelapse.py
12:05:29 | Please move or remove them before you merge.
12:05:29 | Aborting
12:05:29 | Updating bb526e0..5d418ac
12:05:29 | Error updating moonraker
12:05:29 | Error updating git repo

**Comment by ghost** [comment]
Same here...

**Comment by JFD8** [comment]
<img width="1512" alt="Capture d’écran 2022-11-07 à 11 43 52" src="https://user-images.githubusercontent.com/76811440/200345980-8f0b0736-05c4-40ce-8ad1-4f8ae9a8c34c.png">

After a bed Leveling, the system restart ( and this message pops up before the dashboard appears)

**Comment by JFD8** [comment]
> Same here...

I succeed by removing the timelapse.py file from the repository moonraker/moonraker/component/ via putty.
You can use the pi user with pwd flsun only if you flash the firmware with indicated procedure https://github.com/Flsun3d/Flsun_Speeder_Pad 

Or, you can use the script https://www.lesimprimantes3d.fr/forum/topic/48910-tuto-flsun-v400-root-access/ to allow root access to user pi and remove the file. 

Thank you Motar Geek and Guilouz
